[tool.poetry]
name = "bgbench"
version = "0.1.0"
description = "A benchmarking tool"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "bgbench"}]

[tool.poetry.dependencies]
python = "^3.11"
aisuite = {version = "^0.1.6", extras = ["anthropic"]}
anthropic = "^0.18.1"


[tool.poetry.group.dev.dependencies]
pyright = "^1.1.391"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
